---
# Update homebrew and upgrade all packages
- community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Ensure blacklisted cask applications are not installed.
  community.general.homebrew_cask: "name={{ item }} state=absent"
  loop: "{{ homebrew_cask_uninstalled_apps }}"

# Loop through all cask apps to install
- community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: present
    install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
  loop: "{{ homebrew_cask_apps }}"

# Loop through all packages to install
- community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    state: present
  loop: "{{ homebrew_installed_packages }}"




#From geerlingguy script

#   # Cask.
#   - name: Ensure blacklisted cask applications are not installed.
#     homebrew_cask: "name={{ item }} state=absent"
#     loop: "{{ homebrew_cask_uninstalled_apps }}"

#  - name: Install configured cask applications.
#    community.general.homebrew:
#       name: "{{ item.name | default(item) }}"
#       state: present
#       # install_options: "{{ item.install_options | default('appdir=' + homebrew_cask_appdir) }}"
#       # accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
#     loop: "{{ homebrew_cask_apps }}"
#     notify:
#       - Clear homebrew cache

  # # Brew.
  # - name: Ensure blacklisted homebrew packages are not installed.
  #   community.general.homebrew: "name={{ item }} state=absent"
  #   loop: "{{ homebrew_uninstalled_packages }}"

  # - name: Ensure configured homebrew packages are installed.
  #   community.general.homebrew:
  #     name: "{{ item.name | default(item) }}"
  #     # install_options: "{{ item.install_options | default(omit) }}"
  #     state: present
  #   loop: "{{ homebrew_installed_packages }}"
  #   notify:
  #     - Clear homebrew cache